language: php

php:
  - 5.5
  - 5.6

before_install:  
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-id

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit