language: php

php:
  - 5.5.9
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: 5.5.9
      env: setup=stable

before_install:  
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-id

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit